### ISSUE TITLE
Allow airgapped deployments

### ISSUE THREAD

**Issue by jecnua** [seriohub/velero-api#11]
Hi,

One way which is common to raise the security posture of a deployment is to use network policies to close down unneeded access to/from a pod. In a case like velero-api, which wraps calls to velero cli to manage velero resources (and has a relative high level of access to the cluster https://github.com/seriohub/velero-api/issues/10), I would expect it to be able to close down any access to/from the internet to the pod (allowing the velero UI pod of course).

I do understand that at the moment the velero cli is downloaded at runtime by the app. When I close down external access, the pod fails to start:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xffff81f56380>: Failed to establish a new connection: [Errno 111] Connection refused
```

In the README there is a descriptions which says:

```
In the event of a connection problem, the version 1.12.1 contained within the Velero API image will be utilized.
```

However I didn't see the pod stabilise after the errors. There is any way to point the app to a specific executable and completely avoid the download steps?

I can see there are many variables like VELERO_CLI_PATH so maybe there is already a way in which I can pass the executable to the pod (I can use initcontainer to pull it down or some other way which I can sort out with some time). Do you have any guidance on how to solve this issue?

Thank you all for your time.

**Comment by lucianoserio** [comment]
Hi,

We will try to solve the reported error. Currently, if you want to avoid downloading files, you can use the key SKIP_DOWNLOAD=true (not yet documented).
In the future, an additional folder (exposed by the pod) will be available to manually upload the new velero binaries files. However, we will also change the sequence control before attempting to re-download the file.

Regards

**Comment by davideserio** [comment]
Hello,

Version 0.1.4 of both Velero-API and [Velero-UI](https://github.com/seriohub/velero-ui) has been released, introducing [new features and fixes](https://github.com/seriohub/velero-api/blob/main/CHANGELOG.md), including the ability to add a custom folder to load Velero file in air-gapped mode.

In the custom folder, download and copy the .tar.gz files from the Velero GitHub repository, ensuring they match the specified version in **VELERO_CLI_VERSION** and are compatible with your platform (maybe arm64).

The software now searches for the specified version **VELERO_CLI_VERSION** in the following folders, in order:

- VELERO_CLI_PATH_CUSTOM
- VELERO_CLI_PATH
- DOWNLOAD
