### ISSUE TITLE
Good documentation required for configure this in any K8s cluster 

### ISSUE THREAD

**Issue by kansal-mukul** [seriohub/velero-api#22]
Please add proper documentaion with example or create a short video and share with us

**Comment by davideserio** [comment]
Hi,

Currently, we're working on implementing some improvements that I hope we'll be able to release in the next few days. Additionally, we'll gradually expand the documentation.

For deploying to any cluster, you can utilize [velero-helm](https://github.com/seriohub/velero-helm). There's an [values-override.yaml](https://github.com/seriohub/velero-helm/blob/main/values-override.yaml) file available that includes the necessary keys for configuring the deployment of [velero-api](https://github.com/seriohub/velero-api), [velero-ui](https://github.com/seriohub/velero-ui), and [velero-watchdog](https://github.com/seriohub/velero-watchdog).
