### ISSUE TITLE
Move api to /api prefix

### ISSUE THREAD

**Issue by hoerup** [seriohub/velero-api#23]
Just an idea: maybe move all api endpoints to a /api prefix then you could rework helm ingress objects to use just one domain

50_ingress.yaml:
  path: /api
  pathType: Prefix
150_ingress.yaml:
  path: / # as it is currently
  pathType: Prefix

**Comment by davideserio** [comment]
Hi,
Any idea or suggestion is always welcome as a cue for improvement.
In the short term, we are unable to test it, but we will conduct some testing as soon as possible.
