### ISSUE TITLE
k8s cluster with no access to internet

### ISSUE THREAD

**Issue by gabrielfsousa** [seriohub/velero-api#32]
can you add exception options when the cluster dont have access to the internet ?

**Comment by davideserio** [comment]
Hi,

The software uses the internet connection for 3 main purposes:

- At startup, to download the client with the specified version (OPTION VELERO_CLI_VERSION, see [readme](https://github.com/seriohub/velero-api)).
- To send notifications ([watchdog](https://github.com/seriohub/velero-watchdog), in case you use it together with velero-api).
- To perform checks for new available versions.

I understand that there are isolated clusters or that you may want to limit connectivity, which would also limit some functionality.

Currently, the software is mainly designed with the assumption of internet connectivity. However, it should work by foregoing notifications related to backups/restores/schedules operations and updates.

Regarding the specific version, in the case of no connectivity, there are 2 options:

- Use the custom folder (OPTION VELERO_CLI_PATH_CUSTOM, see [readme](https://github.com/seriohub/velero-api) to be mounted at the startup of the pod).
- Use the fallback client (velero client 1.12.1 contained within the Velero API image).

Everything else should function without issues.

We are currently working on a solution for multi-cluster monitoring and cannot conduct extensive tests for isolated cluster. Nevertheless, if you encounter any errors and report them here, we can consider possible solutions.
