### ISSUE TITLE
Add new velero client

### ISSUE THREAD

**Issue by mehdi-aghayari** [seriohub/velero-api#39]
please add new velero client v1.15.0 to velero-api, i can't upload the version in fork of the repository, because it's bigger than 25 MB.

velero link:
https://github.com/vmware-tanzu/velero/releases/download/v1.15.0/velero-v1.15.0-linux-amd64.tar.gz

**Comment by davideserio** [comment]
If you installed Velero via Helm, to select the version of the Velero client, simply set the [apiConfig.veleroCliVersion](https://github.com/seriohub/velero-helm/blob/42297c253704ea6a53fb5761398be343007d6f72/values-override.yaml#L20C3-L20C19) key. When the pod starts, the specified version will be downloaded automatically.
