### ISSUE TITLE
Support for multiarch container

### ISSUE THREAD

**Issue by jecnua** [seriohub/velero-api#4]
Hi all,

I think the project could gain by pushing also arm images on docker hub for people testing on raspberry pis or similar devices. You can plug it easily into a `main` github actions workflow using https://docs.docker.com/build/ci/github-actions/multi-platform/ (so you don't have to manage the build-push yourself) for free.

Thanks for all the work and have a nice day.

**Comment by davideserio** [comment]
Thank you for your valuable suggestion.
We will aim to integrate this functionality in the upcoming updates of the project (for both velero-api and [velero-ui](https://github.com/seriohub/velero-ui)).

If you have any further suggestions or questions, please don't hesitate to reach out.

Have a great day.

**Comment by jecnua** [comment]
Yes, I can confirm the containers start correctly on the RaspberryPIs. Thank you :)
